#!/usr/bin/env node
/**
 * Export contract ABIs from Foundry build output to TypeScript const assertions
 * Usage: node scripts/export-abis.mjs
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONTRACTS_DIR = join(__dirname, '..');
const OUT_DIR = join(CONTRACTS_DIR, 'out');
const ABI_PKG_DIR = join(CONTRACTS_DIR, '..', 'contracts-abi', 'src', 'abis');

// Contracts to export
const CONTRACTS = [
  { name: 'KiteRegistry', file: 'KiteRegistry.sol/KiteRegistry.json' },
  {
    name: 'KiteBaseRegistrar',
    file: 'KiteBaseRegistrar.sol/KiteBaseRegistrar.json',
  },
  { name: 'KiteController', file: 'KiteController.sol/KiteController.json' },
  { name: 'KiteResolver', file: 'KiteResolver.sol/KiteResolver.json' },
  {
    name: 'KiteReverseRegistrar',
    file: 'KiteReverseRegistrar.sol/KiteReverseRegistrar.json',
  },
  {
    name: 'IPriceOracle',
    file: 'IPriceOracle.sol/IPriceOracle.json',
  },
];

function main() {
  // Ensure output directory exists
  if (!existsSync(ABI_PKG_DIR)) {
    mkdirSync(ABI_PKG_DIR, { recursive: true });
  }

  console.log('Exporting ABIs from Foundry build output...\n');

  const exports = [];

  for (const contract of CONTRACTS) {
    const artifactPath = join(OUT_DIR, contract.file);

    if (!existsSync(artifactPath)) {
      console.warn(`  SKIP: ${contract.name} (artifact not found)`);
      continue;
    }

    const artifact = JSON.parse(readFileSync(artifactPath, 'utf-8'));
    const abi = artifact.abi;

    const tsContent = `// Auto-generated by export-abis.mjs — do not edit manually
export const ${contract.name}Abi = ${JSON.stringify(abi, null, 2)} as const;
`;

    const outPath = join(ABI_PKG_DIR, `${contract.name}.ts`);
    writeFileSync(outPath, tsContent);
    exports.push(contract.name);
    console.log(`  ✓ ${contract.name} (${abi.length} entries)`);
  }

  // Generate index file
  const indexContent = exports
    .map((name) => `export { ${name}Abi } from "./abis/${name}.js";`)
    .join('\n');

  const indexPath = join(ABI_PKG_DIR, '..', 'index.ts');
  const fullIndex = `// Auto-generated by export-abis.mjs — do not edit manually
${indexContent}
export { addresses } from "./addresses.js";
`;

  writeFileSync(indexPath, fullIndex);
  console.log(`\n✓ Exported ${exports.length} ABIs to ${ABI_PKG_DIR}`);
}

main();
