// Generated by fumadocs-mdx during `next build` / `next dev`.
// Stub satisfies TypeScript at typecheck time.
declare module '@/.source' {
  // biome-ignore lint/suspicious/noExplicitAny: generated module stub
  export declare const docs: {
    toFumadocsSource: () => any;
  };
}
