// Generated by fumadocs-mdx during `next build` / `next dev`.
// Stub satisfies TypeScript at typecheck time.
declare module '@/.source' {
  export declare const docs: {
    // biome-ignore lint/suspicious/noExplicitAny: generated module stub
    toFumadocsSource: () => any;
  };
}
