// Auto-generated by export-abis.mjs — do not edit manually
export const KiteResolverAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_registry',
        type: 'address',
        internalType: 'contract IKiteRegistry',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addr',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address payable',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'addr',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'coinType',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'clearRecords',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'contenthash',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'interfaceImplementer',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'interfaceID',
        type: 'bytes4',
        internalType: 'bytes4',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [
      {
        name: 'data',
        type: 'bytes[]',
        internalType: 'bytes[]',
      },
    ],
    outputs: [
      {
        name: 'results',
        type: 'bytes[]',
        internalType: 'bytes[]',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'name',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'recordVersions',
    inputs: [
      {
        name: '',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registry',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IKiteRegistry',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setAddr',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'coinType',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'a',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAddr',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'a',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setContenthash',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'hash',
        type: 'bytes',
        internalType: 'bytes',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setInterface',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'interfaceID',
        type: 'bytes4',
        internalType: 'bytes4',
      },
      {
        name: 'implementer',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setName',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'newName',
        type: 'string',
        internalType: 'string',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setText',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'key',
        type: 'string',
        internalType: 'string',
      },
      {
        name: 'value',
        type: 'string',
        internalType: 'string',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [
      {
        name: 'interfaceID',
        type: 'bytes4',
        internalType: 'bytes4',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool',
      },
    ],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'text',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'key',
        type: 'string',
        internalType: 'string',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'AddrChanged',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'a',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AddressChanged',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'coinType',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newAddress',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ContenthashChanged',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'hash',
        type: 'bytes',
        indexed: false,
        internalType: 'bytes',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'InterfaceChanged',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'interfaceID',
        type: 'bytes4',
        indexed: true,
        internalType: 'bytes4',
      },
      {
        name: 'implementer',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NameChanged',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'name',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TextChanged',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'indexedKey',
        type: 'string',
        indexed: true,
        internalType: 'string',
      },
      {
        name: 'key',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
      {
        name: 'value',
        type: 'string',
        indexed: false,
        internalType: 'string',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'Unauthorized',
    inputs: [
      {
        name: 'node',
        type: 'bytes32',
        internalType: 'bytes32',
      },
      {
        name: 'caller',
        type: 'address',
        internalType: 'address',
      },
    ],
  },
] as const;
