// Auto-generated by export-abis.mjs — do not edit manually
export const IPriceOracleAbi = [
  {
    type: 'function',
    name: 'price',
    inputs: [
      {
        name: 'name',
        type: 'string',
        internalType: 'string',
      },
      {
        name: 'expires',
        type: 'uint256',
        internalType: 'uint256',
      },
      {
        name: 'duration',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [
      {
        name: 'price',
        type: 'tuple',
        internalType: 'struct IPriceOracle.Price',
        components: [
          {
            name: 'base',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'premium',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
] as const;
